export { h } from './h'
export { renderSlots } from './helpers/renderSlots'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
export { inject, provide } from './apiInject'
export { createRenderer } from './renderer'